force-app/main/default/objects/CampaignUserJunction__c/CampaignUserJunction__c.object-meta.xml
<CustomObject>
    <description>Helper Object for the Many-to-Many Relationship between Campaigns and Users</description>
    <label>Kampagnen-User-Beziehung</label>
    <nameField>
        <displayFormat>KUB-{0000}</displayFormat>
        <label>Kampagnen-User-Beziehungs-Nummer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kampagnen-User-Beziehungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CampaignUserJunction__c/fields/Kampagne__c.field-meta.xml
<CustomField>
    <fullName>Kampagne__c</fullName>
    <label>Kampagne</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>User</relationshipLabel>
    <relationshipName>CampaignUserJunctions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CampaignUserJunction__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CampaignUserJunctions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestTriggerLaunchCampaignFlow.cls
@isTest
private class TestTriggerLaunchCampaignFlow {
    @isTest static void testInsertCampaignUserJunction() {
        Campaign c = new Campaign(Name = 'Test Campaign');
        insert c;
        
        Profile sysadmin = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        User u = [SELECT Id FROM User WHERE ProfileId = :sysadmin.Id AND isActive = TRUE LIMIT 1];

        CampaignUserJunction__c cuj = new CampaignUserJunction__c(
            User__c = u.Id,
            Kampagne__c = c.Id
        );
        
        Test.startTest();
        insert cuj;
        Test.stopTest();
        
		Campaign cAfterInsert = [SELECT users_on_campaign__c FROM campaign WHERE id = :c.id];

        System.assert(!String.isEmpty(cAfterInsert.users_on_campaign__c));
    }
}