force-app/main/default/objects/Account/recordTypes/Consulting.recordType-meta.xml
<RecordType>
    <fullName>Consulting</fullName>
    <active>true</active>
    <label>Consulting</label>
</RecordType>

force-app/main/default/objects/Goal__c/Goal__c.object-meta.xml
<CustomObject>
    <label>Ziel</label>
    <nameField>
        <label>Ziel-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ziele</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Goal__c/fields/Betrag_im_Zielmonat__c.field-meta.xml
<CustomField>
    <fullName>Betrag_im_Zielmonat__c</fullName>
    <label>Betrag im Zielmonat</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Monat__c.field-meta.xml
<CustomField>
    <fullName>Monat__c</fullName>
    <label>Monat</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Monatsziel__c.field-meta.xml
<CustomField>
    <fullName>Monatsziel__c</fullName>
    <label>Monatsziel</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <label>Record Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
                <default>true</default>
                <label>All</label>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Tech</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Consulting.recordType-meta.xml
<RecordType>
    <fullName>Consulting</fullName>
    <active>true</active>
    <businessProcess>Consulting</businessProcess>
    <label>Consulting</label>
</RecordType>

force-app/main/default/objects/Opportunity_LI_Monthly_Booking__c/Opportunity_LI_Monthly_Booking__c.object-meta.xml
<CustomObject>
    <description>Helper object that allows to break down payments in monthly intervals.</description>
    <label>Monatsbuchung</label>
    <nameField>
        <displayFormat>MB-{000000}</displayFormat>
        <label>Opportunity_LI_Monthly_Booking-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monatsbuchungen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_LI_Monthly_Booking__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Betrag</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_LI_Monthly_Booking__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <description>month in which pro rate payment is due.</description>
    <label>Monat</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity_LI_Monthly_Booking__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Monatsbuchungen</relationshipLabel>
    <relationshipName>Monatsbuchungen</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestGetAmountUponGoalCreation.cls
@IsTest
private class TestGetAmountUponGoalCreation {
    @IsTest
    static void testGetAmountUponGoalCreation(){
        Account acc = new Account(
        	Name = 'Test Account'
        );
        insert acc;
        
        Opportunity opp = new Opportunity(
        	Name = 'Test Opp',
            StageName = 'Closed Won',
            CloseDate = date.parse('01.02.2020'),
            Account = acc
        );
        insert opp;

        Opportunity_LI_Monthly_Booking__c monthlyBooking = new Opportunity_LI_Monthly_Booking__c(
            Month__c = date.parse('01.02.2020'),
            Amount__c = 2000,
            Opportunity__c = opp.id
        );
        insert monthlyBooking;

        Goal__c goal = new Goal__c(
            Name = 'Test Goal',
            Monatsziel__c = 2000,
            Monat__c = date.parse('01.02.2020'),
            Record_Type__c = 'All'
        );

        insert goal;

        Goal__c goalAfterInsert = [SELECT Id, Betrag_im_Zielmonat__c FROM Goal__c WHERE Id = :goal.Id LIMIT 1];
        System.debug(goalAfterInsert);
        System.assert(goalAfterInsert.Betrag_im_Zielmonat__c == 2000);

        goal = new Goal__c(
            Name = 'Test Goal',
            Monatsziel__c = 2000,
            Monat__c = date.parse('01.02.2020'),
            Record_Type__c = 'Consulting'
        );

        insert goal;

        goalAfterInsert = [SELECT Id, Betrag_im_Zielmonat__c FROM Goal__c WHERE Id = :goal.Id LIMIT 1];
        System.debug(goalAfterInsert);
        System.assert(goalAfterInsert.Betrag_im_Zielmonat__c == 2000);
    }
}