force-app/main/default/objects/Opportunity/fields/Expected_Amount__c.field-meta.xml
<CustomField>
    <fullName>Expected_Amount__c</fullName>
    <label>Erwarteter Betrag</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loss_Reason__c.field-meta.xml
<CustomField>
    <fullName>Loss_Reason__c</fullName>
    <label>Grund für Verlust</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Postponed</fullName>
                <label>Verschoben</label>
            </value>
            <value>
                <fullName>No Decision / Non-Responsive</fullName>
                <label>Keine Entscheidung</label>
            </value>
            <value>
                <fullName>Lost to Competitor</fullName>
                <label>An Wettbewerber verloren</label>
            </value>
            <value>
                <fullName>Ansprechpartner gewechselt</fullName>
            </value>
            <value>
                <fullName>No Budget / Lost Funding</fullName>
                <label>Kein Budget</label>
            </value>
            <value>
                <fullName>Price</fullName>
                <label>Preis</label>
            </value>
            <value>
                <fullName>Entscheider nicht überzeugt</fullName>
            </value>
            <value>
                <fullName>Keine Antwort</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <label>Andere</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <businessProcess>Consulting</businessProcess>
    <description>Reden und Immobilien</description>
    <label>Other</label>
</RecordType>

force-app/main/default/classes/TestOppForecastCalculator.cls
@isTest
private class TestOppForecastCalculator {
    public static String CRON_EXP = '0 0 0 15 3 ? 2022';
    @isTest static void testScheduledMethod() {
        String[] stages = new List<String>();
        stages.add('Pitch');
        stages.add('Closed Won');
        stages.add('Closed Lost');

        String[] sources = new List<String>();
        sources.add('Netzwerk (CK)');
        sources.add('Importiert');
        sources.add('Vortrag (CK)');
        sources.add('Kundenempfehlung');

        List<Opportunity> opps = new List<Opportunity>();
        for (Integer i=1; i<=60; i++) {
            Opportunity opp = new Opportunity(
                Name = 'Opportunity ' + i,
                CloseDate = Date.today(),
                Amount = 2000 * i,
                StageName = stages[Math.mod(i, stages.size())],
                LeadSource = sources[Math.mod(i, sources.size())],
                Loss_Reason__c = 'Other'
            );
            opps.add(opp);
        }
        insert opps;

        Test.startTest();
        String jobId = System.schedule('ScheduledApexTest',
            CRON_EXP,
            new ScheduledOppForecastCalculator());
        Test.stopTest();

        List<Opportunity> oppsAfterUpdate = [SELECT id, expected_amount__c FROM opportunity];
        for (Opportunity opp : oppsAfterUpdate) {
            System.debug(opp.expected_amount__c);
        }
    }
}