force-app/main/default/objects/Goal__c/Goal__c.object-meta.xml
<CustomObject>
    <label>Ziel</label>
    <nameField>
        <label>Ziel-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ziele</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Goal__c/fields/Betrag_im_Zielmonat__c.field-meta.xml
<CustomField>
    <fullName>Betrag_im_Zielmonat__c</fullName>
    <label>Betrag im Zielmonat</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Monat__c.field-meta.xml
<CustomField>
    <fullName>Monat__c</fullName>
    <label>Monat</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Monatsziel__c.field-meta.xml
<CustomField>
    <fullName>Monatsziel__c</fullName>
    <label>Monatsziel</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_LI_Monthly_Booking__c/Opportunity_LI_Monthly_Booking__c.object-meta.xml
<CustomObject>
    <description>Helper object that allows to break down payments in monthly intervals.</description>
    <label>Monatsbuchung</label>
    <nameField>
        <displayFormat>MB-{000000}</displayFormat>
        <label>Opportunity_LI_Monthly_Booking-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monatsbuchungen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_LI_Monthly_Booking__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Betrag</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_LI_Monthly_Booking__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <description>month in which pro rate payment is due.</description>
    <label>Monat</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TestUpdateMonthlyGoalTrigger.cls
@isTest
private class TestUpdateMonthlyGoalTrigger {
    @isTest static void testInsertMonthlyBooking() {

        Goal__c monthlyGoal = new Goal__c(
            Name = 'asd',
            Monatsziel__c = 2000,
            Monat__c = date.parse('01.02.2020'),
            Betrag_im_Zielmonat__c = 0
        );
        insert monthlyGoal;

        Opportunity_LI_Monthly_Booking__c monthlyBooking = new Opportunity_LI_Monthly_Booking__c(
            Month__c = date.parse('01.02.2020'),
            Amount__c = 2000
        );

        Goal__c goalBeforeInsert = [SELECT id, Betrag_im_Zielmonat__c, Monat__c FROM Goal__c WHERE Monat__c = :monthlyBooking.Month__c LIMIT 1];
        System.debug(goalBeforeInsert.Betrag_im_Zielmonat__c);

        Test.startTest();
        insert monthlyBooking;
        Test.stopTest();

        Goal__c goalAfterInsert = [SELECT id, Betrag_im_Zielmonat__c, Monat__c FROM Goal__c WHERE Monat__c = :monthlyBooking.Month__c LIMIT 1];
        System.debug(goalAfterInsert.Betrag_im_Zielmonat__c);

        System.assert(goalBeforeInsert.Betrag_im_Zielmonat__c < goalAfterInsert.Betrag_im_Zielmonat__c);
    }
}