force-app/main/default/objects/Goal__c/Goal__c.object-meta.xml
<CustomObject>
    <label>Ziel</label>
    <nameField>
        <label>Ziel-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ziele</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Goal__c/fields/Betrag_im_Zielmonat__c.field-meta.xml
<CustomField>
    <fullName>Betrag_im_Zielmonat__c</fullName>
    <label>Betrag im Zielmonat</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Monat__c.field-meta.xml
<CustomField>
    <fullName>Monat__c</fullName>
    <label>Monat</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <label>Record Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
                <default>true</default>
                <label>All</label>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Tech</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_LI_Monthly_Booking__c/Opportunity_LI_Monthly_Booking__c.object-meta.xml
<CustomObject>
    <description>Helper object that allows to break down payments in monthly intervals.</description>
    <label>Monatsbuchung</label>
    <nameField>
        <displayFormat>MB-{000000}</displayFormat>
        <label>Opportunity_LI_Monthly_Booking-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monatsbuchungen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_LI_Monthly_Booking__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Betrag</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_LI_Monthly_Booking__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <description>month in which pro rate payment is due.</description>
    <label>Monat</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity_LI_Monthly_Booking__c/fields/Opp_is_Closed_Won__c.field-meta.xml
<CustomField>
    <fullName>Opp_is_Closed_Won__c</fullName>
    <formula>ISPICKVAL(Opportunity__r.StageName, &#39;Closed Won&#39;)</formula>
    <label>Opp is Closed Won</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity_LI_Monthly_Booking__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Monatsbuchungen</relationshipLabel>
    <relationshipName>Monatsbuchungen</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MonthlyGoalUpdater.cls
global class MonthlyGoalUpdater {
    public static void updateMonthlyGoal(List<Opportunity_LI_Monthly_Booking__c> bookingList) {
        for (Opportunity_LI_Monthly_Booking__c monthlyBooking : bookingList) {
            Opportunity opp = [SELECT Id, RecordTypeId FROM Opportunity WHERE Id = :monthlyBooking.Opportunity__c][0];
            String oppRecordTypeName = Schema.SObjectType.Opportunity.getRecordTypeInfosById().get(opp.RecordTypeId).getName();

            try {
                AggregateResult monthlyBookingsByMonth = [
                    SELECT Month__c, SUM(Amount__c)
                    FROM Opportunity_LI_Monthly_Booking__c
                    WHERE Month__c = :monthlyBooking.Month__c
                        AND opp_is_closed_won__c = TRUE
                    GROUP BY Month__c
                    LIMIT 1
                ];
                Double monthlyBookingsAmountInMonth = (Double) monthlyBookingsByMonth.get('expr0');
                Goal__c monthlyGoal = [SELECT Id FROM Goal__c WHERE Monat__c = :monthlyBooking.Month__c AND Record_Type__c = 'All' LIMIT 1];
                monthlyGoal.Betrag_im_Zielmonat__c = monthlyBookingsAmountInMonth;
                update monthlyGoal;
            } catch (QueryException e) {
                System.debug(e.getMessage());
            }

            try {
                AggregateResult monthlyBookingsByMonthRT = [
                    SELECT Month__c, SUM(Amount__c)
                    FROM Opportunity_LI_Monthly_Booking__c
                    WHERE Month__c = :monthlyBooking.Month__c
                        AND opp_is_closed_won__c = TRUE
                        AND Opportunity__r.RecordTypeId = :opp.RecordTypeId
                    GROUP BY Month__c
                    LIMIT 1
                ];
                Double monthlyBookingsAmountInMonthRT = (Double) monthlyBookingsByMonthRT.get('expr0');
                Goal__c monthlyGoalRT = [SELECT Id FROM Goal__c WHERE Monat__c = :monthlyBooking.Month__c AND Record_Type__c = :oppRecordTypeName LIMIT 1];
                monthlyGoalRT.Betrag_im_Zielmonat__c = monthlyBookingsAmountInMonthRT;
                update monthlyGoalRT;
            } catch (QueryException e) {
                System.debug(e.getMessage());
            }
        }
    }
}