force-app/main/default/objects/Data_Snapshot__c/Data_Snapshot__c.object-meta.xml
<CustomObject>
    <label>Data Snapshot</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>Data Snapshot Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Snapshot__c/fields/Open_Opps__c.field-meta.xml
<CustomField>
    <fullName>Open_Opps__c</fullName>
    <label>Open Opps</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Data_Snapshot__c/fields/Total_Pipeline__c.field-meta.xml
<CustomField>
    <fullName>Total_Pipeline__c</fullName>
    <label>Total Pipeline</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Data_Snapshot__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Actual</fullName>
            </value>
            <value>
                <fullName>Average</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Data_Snapshot__c/fields/User_Snapshot__c.field-meta.xml
<CustomField>
    <fullName>User_Snapshot__c</fullName>
    <defaultValue>false</defaultValue>
    <label>User Snapshot</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SnapshotSettings__c/SnapshotSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Data Snapshot Settings</label>
</CustomObject>

force-app/main/default/objects/SnapshotSettings__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>User Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TestDataSnapshot.cls
@isTest
private class TestDataSnapshot {
    @isTest
    static void testDataSnapshot() {
        Account acc = new Account(
            Name = 'Test Acc'
        );
        insert acc;

        for (Integer i = 1; i <= 5; i++) {
            Opportunity opp = new Opportunity(
                Name = 'Test Opp',
                StageName = 'Pitch',
                CloseDate = Date.today(),
                Amount = 100,
                Account = acc
            );
            insert opp;
        }

        SnapshotSettings__c setting = new SnapshotSettings__c(
            Name = 'Test',
            User_Id__c = UserInfo.getUserId()
        );
        insert setting;

        Test.startTest();
        System.schedule('ScheduledApexTest', '0 0 0 15 3 ? 2022', new ScheduledDataSnapshot());
        Test.stopTest();

        Data_Snapshot__c snap = [
            SELECT Id, Open_Opps__c, Total_Pipeline__c 
            FROM Data_Snapshot__c
            WHERE Type__c = 'Actual'
                AND User_Snapshot__c = false
            LIMIT 1
        ];

        System.assert(snap.Open_Opps__c == 5);
        System.assert(snap.Total_Pipeline__c == 500);
    }
}